version: "3.8"

services:
  planka:
    build: .
    restart: on-failure
    volumes:
      - favicons:/app/public/favicons
      - user-avatars:/app/public/user-avatars
      - background-images:/app/public/background-images
      - attachments:/app/private/attachments
    ports:
      - 3000:1337
    environment:
      - BASE_URL=http://localhost:3000
      - DATABASE_URL=postgresql://postgres@postgres/planka
      - SECRET_KEY=notsecretkey

      # 👤 Default Admin (auto-created on first launch)
      - DEFAULT_ADMIN_EMAIL=admin@wolfco.io
      - DEFAULT_ADMIN_PASSWORD=changeme123
      - DEFAULT_ADMIN_NAME=CorePoint Admin
      - DEFAULT_ADMIN_USERNAME=corepoint_admin

      # 📧 SMTP settings (edit these for your real provider)
      - SMTP_HOST=smtp.example.com
      - SMTP_PORT=587
      - SMTP_SECURE=true
      - SMTP_USER=no-reply@wolfco.io
      - SMTP_PASSWORD=your_smtp_password
      - SMTP_FROM="CorePoint Admin" <no-reply@wolfco.io>

    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16-alpine
    restart: on-failure
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=planka
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d planka"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  favicons:
  user-avatars:
  background-images:
  attachments:
  db-data:
